// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmppbfspayssyqnlswvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tcHBiZnNwYXlzc3lxbmxzd3ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTMyNjMsImV4cCI6MjA2NDYyOTI2M30.3CrB_3nhgkiXFZS4wEMHGorf1i7qBfIADQPzq2x1jTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);